# -*- coding: utf-8 -*-
import sys, os
sys.path.insert(0, os.path.dirname(__file__))
os.chdir(os.path.dirname(os.path.dirname(__file__)))
from _apply import apply

ar = [
"بروية.",
"تستطيع فعل ما هو أكثر بكثير، لو أصلحناها.",
"إنها… ميتة… ميتة. (يسعل)\nالشرارة خُنقت… وابتُلعت",
"همم. لا بد أنها تحبّك.",
"أنا... لم أرَ مثل هذا من قبل.",
"مثير للإعجاب، أليس كذلك؟",
"ألاحظت الحافة المسنّنة الدقيقة؟",
"أخبر الآخرين بما رأيته هنا اليوم!",
"[Falls 2nd Time]",
"[Falls First Time]",
"[10th Dialogue]",
"[11th Dialogue]",
"[12th Dialogue]",
"[12th Dialogue]",
"[13th Dialogue]",
"[14th Dialogue]",
"[15th Dialogue]",
"[4th Dialogue - No Help]",
"[4th Dialogue- Helped Up]",
"[5th Dialogue]",
"[6th Dialogue]",
"[7th Dialogue]",
"[8th Dialogue]",
"[9th Dialogue]",
"[First Dialogue]",
"[Generic - No Finger]",
"[Second Dialogue]",
"[Third Dialogue]",
"[10th Dialogue]",
"[11th Dialogue]",
"[12th Dialogue]",
"[13th Dialogue]",
"[14th Dialogue]",
"[15th Dialogue]",
"[4th Dialogue]",
"[5th Dialogue]",
"[6th Dialogue]",
"[7th Dialogue]",
"[8th Dialogue]",
"[9th Dialogue]",
"[First Dialogue]",
"[Generic - No Finger]",
"[Second Dialogue]",
"[Third Dialogue]",
"[10th Dialogue]",
"[11th Dialogue]",
"[12th Dialogue - Did NOT Give]",
"[12th Dialogue - Gave Finger]",
"[13th Dialogue]",
"[14th Dialogue]",
"[15th Dialogue]",
"[4th Dialogue - Helped Up]",
"[4th Dialogue - No Help]",
"[5th Dialogue]",
"[6th Dialogue]",
"[7th Dialogue]",
"[8th Dialogue]",
"[9th Dialogue]",
"[First Dialogue]",
"[Generic - No Finger]",
]

apply(99, ar)
